blueprint:
  name: 定時溫度檢查並詢問是否開冷氣（含額外設備控制）
  description: >
    在指定星期與時間檢查溫度，若高於設定值，透過 HA Companion App 發送互動通知，詢問是否開冷氣。
    如果選擇開冷氣，會同時控制你指定的其他設備。
  domain: automation
  input:
    notify_device:
      name: 手機推播目標
      description: 要發送通知的裝置（需安裝 HA App）
      selector:
        device:
          integration: mobile_app

    temperature_sensor:
      name: 室內溫度感測器
      description: 用來檢查室溫的 sensor（需有數值）
      selector:
        entity:
          domain: sensor
          device_class: temperature

    climate_entity:
      name: 冷氣設備（ESPHome）
      description: 要控制的冷氣實體（climate 類型）
      selector:
        entity:
          domain: climate

    extra_entities:
      name: 附加設備
      description: 選擇在開冷氣時要一起開啟的裝置（可多選）
      default: []
      selector:
        entity:
          multiple: true

    temperature_threshold:
      name: 溫度門檻
      description: 高於此溫度才會觸發
      default: 28
      selector:
        number:
          min: 20
          max: 35
          step: 0.5
          unit_of_measurement: "°C"

    schedule_days:
      name: 哪些星期要執行？
      selector:
        select:
          multiple: true
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun

    schedule_time:
      name: 幾點幾分執行？
      selector:
        time:

mode: single

variables:
  temperature_sensor_id: !input temperature_sensor
  climate_entity_id: !input climate_entity
  extra_entities_ids: !input extra_entities
  notify_device_id: !input notify_device
  schedule_days: !input schedule_days

trigger:
  - platform: time
    at: !input schedule_time

condition:
  - condition: template
    value_template: >-
      {{ now().strftime('%a') | lower in schedule_days }}
  - condition: numeric_state
    entity_id: "{{ temperature_sensor_id }}"
    above: !input temperature_threshold

action:
  - service: "notify.mobile_app_{{ device_attr(notify_device_id, 'name') | lower | replace(' ', '_') }}"
    data:
      message: >-
        現在室溫是 {{ states(temperature_sensor_id) }}°C，
        要開冷氣嗎？
      title: "冷氣提示"
      data:
        actions:
          - action: "TURN_ON_AC"
            title: "開冷氣"
          - action: "IGNORE"
            title: "不用"

  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "TURN_ON_AC"
    timeout: "00:05:00"
    continue_on_timeout: false

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger is not none }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ climate_entity_id }}"
            data:
              hvac_mode: cool

          - if:
              - condition: template
                value_template: "{{ extra_entities_ids | length > 0 }}"
            then:
              - service: homeassistant.turn_on
                target:
                  entity_id: "{{ extra_entities_ids }}"
