blueprint:
  name: 睡覺模式：關燈、關冷氣與風扇 + 洗碗機門提醒
  description: >
    當 input_boolean.sleep_mode 被打開時：
    1. 關閉所有指定燈（light）與風扇（fan）
    2. 關閉所有指定冷氣（climate）
    3. 如果洗碗機門沒開，播語音提醒
    4. 自動把 input_boolean 關閉（像按鈕）

  domain: automation
  input:
    trigger_input_boolean:
      name: 觸發用的 input_boolean
      selector:
        entity:
          domain: input_boolean

    lights_and_fans_to_turn_off:
      name: 要關閉的燈與風扇（light / fan）
      selector:
        target:
          entity:
            domain:
              - light
              - fan

    aircons_to_turn_off:
      name: 要關閉的冷氣（climate）
      selector:
        target:
          entity:
            domain: climate

    dishwasher_door_sensor:
      name: 洗碗機門感測器（binary_sensor）
      description: 門打開時為 on，關閉為 off
      selector:
        entity:
          domain: binary_sensor

    tts_speaker:
      name: 廣播用的 TTS 裝置
      selector:
        entity:
          domain: media_player

    tts_message:
      name: 提醒語音
      default: "請記得打開洗碗機的門喔。"
      selector:
        text:

mode: single

trigger:
  - platform: state
    entity_id: !input trigger_input_boolean
    to: 'on'

action:
  - service: homeassistant.turn_off
    target: !input lights_and_fans_to_turn_off

  - service: climate.turn_off
    target: !input aircons_to_turn_off

  - condition: state
    entity_id: !input dishwasher_door_sensor
    state: 'off'

  - service: tts.edge_hsiaochen
    data:
      entity_id: !input tts_speaker
      message: !input tts_message

  - delay: "00:00:02"

  - service: input_boolean.turn_off
    target:
      entity_id: !input trigger_input_boolean
