blueprint:
  name: 睡覺模式：一鍵關燈關電 + 洗碗機門提醒
  description: >
    當指定的 input_boolean 被打開（通常代表「我要睡覺」），
    1. 關閉所有指定的 switch 與 light。
    2. 檢查洗碗機門是否開啟（binary_sensor）
    3. 如果沒開，用 TTS 廣播提醒。

  domain: automation
  input:
    trigger_input_boolean:
      name: 觸發用的 input_boolean
      selector:
        entity:
          domain: input_boolean

    targets_to_turn_off:
      name: 要關閉的電器（switch 或 light）
      selector:
        target:
          entity:
            domain:
              - switch
              - light

    dishwasher_door_sensor:
      name: 洗碗機門狀態感測器（binary_sensor）
      description: 門打開時為 on，關閉為 off
      selector:
        entity:
          domain: binary_sensor

    tts_speaker:
      name: 廣播用的 TTS 裝置
      selector:
        entity:
          domain: media_player

    tts_message:
      name: 提醒語音
      default: "請記得打開洗碗機的門喔。"
      selector:
        text:

mode: single

trigger:
  - platform: state
    entity_id: !input trigger_input_boolean
    to: 'on'

action:
  - service: homeassistant.turn_off
    target: !input targets_to_turn_off

  - condition: state
    entity_id: !input dishwasher_door_sensor
    state: 'off'

  - service: tts.google_translate_say
    data:
      entity_id: !input tts_speaker
      message: !input tts_message
